dist: xenial
language: node_js
os: linux
env:
  global:
    - CC_TEST_REPORTER_ID="574209c4867da31240165f5b2e522d3c5c6ba697fd1a77bf31d578ab3675ac02"
jobs:
  include:
  - node_js: '12'
cache:
  directories: [node_modules]
services:
  - postgresql
install:
  - npm install
before_script:
  - psql -c 'create database quotes_test;' -U postgres
  - sequelize db:migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
after_success: npm run coverage
before_deploy:
  - npm install -g serverless
  - export NODE_ENV=production && npm run prestart
deploy:
  provider: script
  script: 
    - sls deploy
  skip_cleanup: true
  on:
    branch: master
after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT