environment:
    matrix:
    - nodejs_version: "12"
install:
  - npm install
test_script:
  - npm test
build: off
before_test:
  - SET PGUSER=postgres
  - SET PGPASSWORD=
  - PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
  - createdb quote_test
services:
  - postgresql101