service: cs3219-otot-taskb

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: production

functions:
  app:
    handler: build/app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline