app: cs3219-otot-taskb-app
service: cs3219-otot-taskb

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: production
  environment:
    NODE_ENV: production
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  app:
    handler: build/app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline